#!/usr/bin/env python3
import base64
import os
import sys
HELP = """Command line utitily to encode or decode data to/from base85 format.
Usage: {name} [command]
Commands:
  --encode - encode input data (from stdin) to the base85 (default)
  --decode - decode input data (from stdin) from the base85
  --help   - show help screen

Examples:
  echo -n "Hello" | base85
  echo -n "87cURDZ" | base85 --decode
  cat sample.txt | base85 > sample-base85.txt
  cat sample-base85.txt | base85 --decode > sample2.txt
"""
cmd = (sys.argv[1] if len(sys.argv) > 1 else '--encode').lower()
if cmd in ['--encode', '-e']:
    sys.stdout.write(base64.a85encode(sys.stdin.read().encode('utf-8'))
                     .decode('utf-8'))
elif cmd in ['--decode', '-d']:
    sys.stdout.write(base64.a85decode(sys.stdin.read().encode('utf-8'))
                     .decode('utf-8'))
elif cmd in ['--help', '-h']:
    print(HELP.format(name=os.path.basename(__file__)))
    sys.exit(1)
else:
    print('Error: unknown command \'{0}\''.format(cmd))
    sys.exit(1)
