baseURL: 'https://example.com'
defaultContentLanguage: en
languageCode: en-us
theme: hugo-notepadium
themesDir: ./themes
title: REvgen
copyright: ©2014-2021 <a href="https://github.com/revgen">Evgen Rusakov</a>
paginate: 25
enableRobotsTXT: false
params:
  assets:
    css:
      - css/site.css
    js:
      - js/site.js
  style: light
  dateFormat: 'Monday, January 2, 2006'
  logo: ''
  slogan: ''
  license: ''
  fullRss: false
  paginate: 1
  comments:
    enable: false
  math:
    enable: false
    use: katex
  syntax:
    use: hljs
    theme: xcode
    darkTheme: xcode-dark
  share:
    enable: false
    addThisId: ''
    inlineToolId: ''
  nav:
    showCategories: false
    showTags: false
    custom:
      - title: "\U0001F4C1"
        url: /categories
      - title: "\U0023"
        url: /tags
      - title: "\U0001F516"
        url: /bookmarks
      - title: "\U0001F6E0"
        url: /tools
markup:
  highlight:
    codeFences: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
