title = "REvgen"
theme = "hugo-coder"
baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"

paginate = 100

[markup.highlight]
style = "monokai"
# style = "github-dark"

[params]
  author = "Evgen Rusakov"
  description = "Evgen's personal website"
  since = 2019

  dateFormat = "January 2, 2006"
  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []
  customRemoteJS = []

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  touchIcon = "/images/apple-touch-icon.png"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/revgen/"

# Menu links
[[menu.main]]
  name = "\U0001F516"
  weight = 1
  url  = "/bookmarks"
[[menu.main]]
  name = "\U0001f4c1"
  weight = 2
  url = "/categories"
[[menu.main]]
  name = "\U00000023"
  weight = 2
  url = "/tags"
#[[menu.main]]
#  name = "\U0001F6E0"
#  weight = 3
#  url  = "/tools"