title = "revgen"
theme = "hugo-coder"
baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 100

[markup.highlight]
style = "monokai"
# style = "github-dark"
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
tabWidth = 2
# example: https://mertbakir.gitlab.io/hugo/syntax-highlighting-in-hugo/
# https://gohugo.io/getting-started/configuration-markup/#highlight

[params]
  title = "Ô˜vgen"
  author = "Evgen Rusakov"
  description = "Evgen's personal website"
  avatarURL = "/assets/img/site.png"
  manifest = "/manifest.json"
  srcUrl = "https://github.com/revgen/revgen.github.io/tree/master/src/content/"

  since = 2019

  dateFormat = "January 2, 2006"
  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["assets/css/site.css"]
  # customSCSS = []
  # customJS = ["assets/js/site.js"]
  # customRemoteJS = []

  faviconSVG = "/assets/img/favicon.svg"
  favicon_32 = "/assets/img/favicon-32x32.png"
  favicon_16 = "/assets/img/favicon-16x16.png"
  touchIcon = "/apple-touch-icon.png"
  mask_icon = "/assets/img/favicon.svg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[outputFormats]
    [outputFormats.manifest]
        name = "manifest"
        baseName = "manifest"
        mediaType = "application/json"
        notAlternative = "true"
    [outputFormats.browserconfig]
        name = "browserconfig"
        baseName = "browserconfig"
        mediaType = "application/xml"
        notAlternative = "true"

[outputs]
    home = [ "HTML", "RSS", "MANIFEST", "BROWSERCONFIG"]

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/revgen/"

# Menu links
[[menu.main]]
  # name = "\U0001F516 Bookmarks"
  name = "Bookmarks"
  weight = 1
  url  = "/bookmarks"
#[[menu.main]]
#  name = "Notes"
#  weight = 2
#  url = "/notes"
[[menu.main]]
  name = "Posts"
  weight = 3
  url = "/posts"
[[menu.main]]
  # name = "\U00000023 Tags"
  name = "Tags"
  weight = 4
  url = "/tags"
[[menu.main]]
  name = "Tools"
  weight = 5
  url  = "/tools"
# [[menu.main]]
  # name = "\U0001f4c1 Categories"
  # name = "CATEGORIES"
  # weight = 3
  # url = "/categories"
