title = "Ô˜vgen"
# title = "REvgen"
theme = "hugo-coder"
baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 100

[markup.highlight]
style = "monokai"
# style = "github-dark"

[params]
  title = "REvgen"
  author = "Evgen Rusakov"
  description = "Evgen's personal website"
  avatarURL = "/assets/img/favicon.png"
  manifest = "/webmanifest.json"

  since = 2019

  dateFormat = "January 2, 2006"
  colorScheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["assets/css/site.css"]
  customSCSS = []
  # customJS = ["assets/js/site.js"]
  customRemoteJS = []

  faviconSVG = "/assets/img/favicon.svg"
  favicon_32 = "/assets/img/favicon-32x32.png"
  favicon_16 = "/assets/img/favicon-16x16.png"
  touchIcon = "/assets/img/favicon-apple-touch.png"
  mask_icon = "/assets/img/favicon.svg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[outputFormats]
    [outputFormats.manifest]
        name = "manifest"
        baseName = "manifest"
        mediaType = "application/json"
        notAlternative = "true"
    [outputFormats.browserconfig]
        name = "browserconfig"
        baseName = "browserconfig"
        mediaType = "application/xml"
        notAlternative = "true"

[outputs]
    home = [ "HTML", "RSS", "MANIFEST", "BROWSERCONFIG"]

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/revgen/"

# Menu links
[[menu.main]]
  # name = "\U0001F516 Bookmarks"
  name = "Bookmarks"
  weight = 1
  url  = "/bookmarks"
[[menu.main]]
  # name = "\U00000023 Tags"
  name = "TAGS"
  weight = 2
  url = "/tags"
[[menu.main]]
  # name = "\U0001f4c1 Categories"
  name = "CATEGORIES"
  weight = 3
  url = "/categories"
#[[menu.main]]
#  name = "\U0001F6E0"
#  weight = 3
#  url  = "/tools"